repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        types_or: [c]

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.4
    hooks:
      - id: typos
        exclude: (docs|config|cert|CMakeLists.txt)
        # NOTE Override hook's default args to prevent automatic
        # fixing of found typos. Let the dev decide what to fix!
        args: ['--force-exclude']
        stages: [commit-msg, pre-commit]
